### ISSUE TITLE
增加腾讯文档隐藏

### ISSUE THREAD

**Issue by PLFJY** [YF-Eternal/Sidebar-Management#1]
新版本出现了腾讯文档的图标，如果可以请推出可以隐藏腾讯文档的版本
![image](https://github.com/user-attachments/assets/7b558d4e-f4c5-4c9b-98be-2a1d263637f3)

**Comment by YF-Eternal** [comment]
应该可以在“更多”选项这里关闭吧。
![1](https://github.com/user-attachments/assets/461bd2a3-20a1-40ec-86df-39341a582d85)

- 但已经有人PR就加入此功能了。(#2 )
- 请查看[Releases](https://github.com/YF-Eternal/Sidebar-Management/releases)新版已加入此功能。
